FROM ros:humble-ros-base

LABEL authors="dadouuu"

EXPOSE 4421

RUN mkdir /home/ros2_ws
RUN mkdir /home/ros2_ws/src
RUN mkdir /home/ros2_ws/src/controller
RUN mkdir /home/ros2_ws/src/controller/resource

WORKDIR /home/ros2_ws/

COPY controller /home/ros2_ws/src/controller/controller/
COPY conf/ /home/ros2_ws/src/controller/conf/
COPY json/ /home/ros2_ws/src/controller/json/
COPY medias/ /home/ros2_ws/src/controller/medias/

COPY conf/ros2/setup.py /home/ros2_ws/src/controller/
COPY conf/ros2/package.xml /home/ros2_ws/src/controller/
COPY conf/ros2/setup.cfg /home/ros2_ws/src/controller/
COPY conf/ros2/resource/controller /home/ros2_ws/src/controller/resource
COPY conf/ros2_dependencies/ /home/ros2_ws/src/

COPY dadou_utils_ros.tar.gz /home/ros2_ws/src/controller/
RUN tar -xzhf /home/ros2_ws/src/controller/dadou_utils_ros.tar.gz -C /home/ros2_ws/src/controller/ && \
    rm /home/ros2_ws/src/controller/dadou_utils_ros.tar.gz

RUN apt-get update && cat /home/ros2_ws/src/controller/conf/packages.txt | xargs apt-get install -y

ENV PYTHONPATH "${PYTHONPATH}:/home/ros2_ws/src"

RUN pip3 install -r /home/ros2_ws/src/controller/conf/requirements.txt

ENV DISPLAY host.docker.internal:0

ENTRYPOINT ["/bin/bash", "-c", "source /home/ros2_ws/src/controller/conf/scripts/run-docker.sh"]

#COPY controller/test.py .
#ENTRYPOINT ["python3", "test.py"]
