services:
  dadou-control:
    container_name: dadou-controller-container
    image: dadouuu/dadou-controller-arm:latest
    build:
      context: ../../..
      dockerfile: conf/docker/arm/Dockerfile-arm
    environment:
      - DISPLAY=${DISPLAY}
    #ports:
    #  - "80:80"
    #  - "8000-9000:8000-9000"
    network_mode: "host"

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/pi/ros2_ws/src/controller/conf:/home/ros2_ws/src/controller/conf
      - /home/pi/ros2_ws/src/controller/controller:/home/ros2_ws/src/controller/controller
      - /home/pi/ros2_ws/src/controller/dadou_utils:/home/ros2_ws/src/controller/dadou_utils
      - /home/pi/ros2_ws/src/controller/json:/home/ros2_ws/src/controller/json
      - /home/pi/ros2_ws/src/controller/medias:/home/ros2_ws/src/controller/medias
    #  - /dev/:/dev
    #  - /dev/null:/folder/fileToBeExcluded
    #accès device ACMO gpio serial by id disque etc ...
    privileged: true
 #   devices:
 #    - /dev
