version: '3'
services:
  dadou-control:
    build: ../..
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    #  - /dev/:/dev
    #  - /dev/null:/folder/fileToBeExcluded
    #accès device ACMO gpio serial by id disque etc ...
    privileged: true
 #   devices:
 #    - /dev